title: Ensemble Prediction of Task Affinity for Efficient Multi-Task Learning
description: This repository contains the code and data for the paper “Ensemble Prediction of Task Affinity for Efficient Multi-Task Learning”, published at the 14th International Conference on Learning Representations (ICLR 2026).
